### ISSUE TITLE
Newbie problem

### ISSUE THREAD

**Issue by pervrosen** [yveshauser/quandl-api-v3#1]
Using Aeson>=2.0.0.0 I get an error building, but if I change [Quandl.hs](https://github.com/yveshauser/quandl-api-v3/blob/master/src/Data/Quandl.hs) 
row 210: HM.lookup -> Data.Aeson.KeyMap.lookup (also import new Aeson) I can compile. Can you update this lib to work using new Aeson>=2.0.0.0 pls? (I am not 100% I did correct also...)

**Comment by yveshauser** [comment]
In order to properly build the project, I recommend to use `nix`. The README file is updated with the instructions to do so.
